# Generated by Django 3.2.9 on 2021-11-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugList',
            fields=[
                ('sku_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='SKU ID')),
                ('product_id', models.IntegerField(null=True, verbose_name='Product ID')),
                ('sku_name', models.CharField(max_length=200, null=True, verbose_name='SKU Name')),
                ('price', models.CharField(max_length=200, null=True, verbose_name='Price')),
                ('manufacturer_name', models.CharField(max_length=200, null=True, verbose_name='Manufacturer Name')),
                ('salt_name', models.CharField(max_length=200, null=True, verbose_name='Salt Name')),
                ('drug_form', models.CharField(max_length=200, null=True, verbose_name='Drug Form')),
                ('Pack_size', models.CharField(max_length=200, null=True, verbose_name='Pack Size')),
                ('strength', models.CharField(max_length=200, null=True, verbose_name='Strength')),
                ('product_banned_flag', models.CharField(max_length=200, null=True, verbose_name='Ban')),
                ('unit', models.CharField(max_length=200, null=True, verbose_name='unit')),
                ('price_per_unit', models.CharField(max_length=200, null=True, verbose_name='Price Per Unit')),
            ],
            options={
                'ordering': ['product_id'],
            },
        ),
    ]
